<#
  Discovers Hyper-V guest IPs for lab VMs and writes an Ansible inventory YAML.

  Hyper-V KVP often reports a stale IP from the golden image on every clone until
  cloud-init finishes DHCP. We only accept an address once it is unique across
  the VM set (duplicates keep waiting).
#>
param(
  [Parameter(Mandatory = $true)]
  [string[]]$VmNames,

  [Parameter(Mandatory = $true)]
  [string]$OutputPath,

  [string]$SshUser = "ubuntu",
  [string]$SshPrivateKeyPath = "",
  [int]$WaitSeconds = 300,
  [int]$PollSeconds = 10
)

$ErrorActionPreference = "Stop"

function Get-GuestIpv4 {
  param([string]$Name)
  $adapters = @(Get-VMNetworkAdapter -VMName $Name -ErrorAction SilentlyContinue)
  if ($adapters.Count -eq 0) { return $null }
  foreach ($adapter in $adapters) {
    $ips = @($adapter.IPAddresses | Where-Object {
        $_ -match '^\d+\.\d+\.\d+\.\d+$' -and $_ -notlike '169.254.*'
      })
    if ($ips.Count -gt 0) { return $ips[0] }
  }
  return $null
}

$deadline = (Get-Date).AddSeconds($WaitSeconds)
$resolved = @{}
# One soft reboot for guests still without a unique IP after this many seconds
# (stuck cloud-init / networking often recovers after Restart-VM).
$restartAfterSeconds = [Math]::Min(120, [Math]::Max(60, [int]($WaitSeconds / 3)))
$restarted = @{}

Write-Host "Waiting up to $WaitSeconds seconds for unique guest IPs..."
while ((Get-Date) -lt $deadline) {
  # Fresh read every poll — do not trust earlier KVP values (golden-image ghosts).
  $current = @{}
  foreach ($name in $VmNames) {
    $ip = Get-GuestIpv4 -Name $name
    if ($ip) { $current[$name] = $ip }
  }

  $ipCounts = @{}
  foreach ($ip in $current.Values) {
    if (-not $ipCounts.ContainsKey($ip)) { $ipCounts[$ip] = 0 }
    $ipCounts[$ip]++
  }

  $prevResolved = $resolved
  $resolved = @{}
  $pending = @()
  foreach ($name in $VmNames) {
    if (-not $current.ContainsKey($name)) {
      $pending += $name
      continue
    }
    $ip = $current[$name]
    if ($ipCounts[$ip] -eq 1) {
      $resolved[$name] = $ip
      if (-not $prevResolved.ContainsKey($name) -or $prevResolved[$name] -ne $ip) {
        Write-Host "  $name -> $ip"
      }
    } else {
      Write-Host "  $name -> $ip (shared by $($ipCounts[$ip]) VMs; waiting for unique DHCP lease)"
      $pending += $name
    }
  }

  if ($pending.Count -eq 0) { break }

  $elapsed = $WaitSeconds - ($deadline - (Get-Date)).TotalSeconds
  if ($elapsed -ge $restartAfterSeconds) {
    foreach ($name in $pending) {
      if ($restarted.ContainsKey($name)) { continue }
      $vm = Get-VM -Name $name -ErrorAction SilentlyContinue
      if (-not $vm) { continue }
      Write-Host "  no unique IP yet for $name after ${restartAfterSeconds}s; restarting VM once..."
      try {
        Restart-VM -Name $name -Force -ErrorAction Stop
        $restarted[$name] = $true
      } catch {
        Write-Warning "  Restart-VM failed for ${name}: $_"
      }
    }
  }

  Write-Host ("  still waiting: " + ($pending -join ", "))
  Start-Sleep -Seconds $PollSeconds
}

$missing = @($VmNames | Where-Object { -not $resolved.ContainsKey($_) })
if ($missing.Count -gt 0) {
  throw "Timed out waiting for unique guest IPs: $($missing -join ', '). Ensure VMs are running, hv-kvp is up, and DHCP is handing out distinct leases (not a stale golden-image IP)."
}

# Group by naming convention: <env>-<cluster>-<role>-<n>
$byCluster = @{}
foreach ($name in $VmNames) {
  $parts = $name -split "-"
  if ($parts.Count -lt 4) {
    throw "Unexpected VM name '$name' (expected <env>-<cluster>-<role>-<n>)"
  }
  $cluster = $parts[1]
  $role = $parts[2]
  if (-not $byCluster.ContainsKey($cluster)) {
    $byCluster[$cluster] = @{ masters = @(); workers = @() }
  }
  $entry = @{ name = $name; ip = $resolved[$name]; role = $role }
  if ($role -eq "master") {
    $byCluster[$cluster].masters += $entry
  } else {
    $byCluster[$cluster].workers += $entry
  }
}

$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outDir)) {
  New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$keyLine = if ($SshPrivateKeyPath) {
  # Prefer a key inside the WSL home: OpenSSH rejects world-writable /mnt/c/... keys.
  "    ansible_ssh_private_key_file: ~/.ssh/id_ed25519_lab"
} else {
  ""
}

# First path segment of VM names: dev-cluster1-master-1 → lab_env=dev
$labEnv = (($VmNames | Select-Object -First 1) -split '-')[0]
if ($labEnv -notmatch '^(dev|stable)$') {
  Write-Warning "Could not infer lab_env from VM name; defaulting to 'dev'."
  $labEnv = "dev"
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("---")
[void]$sb.AppendLine("# Generated by discover-inventory.ps1 - do not edit by hand.")
[void]$sb.AppendLine("all:")
[void]$sb.AppendLine("  vars:")
[void]$sb.AppendLine("    ansible_user: $SshUser")
[void]$sb.AppendLine("    ansible_python_interpreter: /usr/bin/python3")
[void]$sb.AppendLine("    lab_env: $labEnv")
if ($keyLine) { [void]$sb.AppendLine($keyLine) }
[void]$sb.AppendLine("  children:")

$clusterNames = @($byCluster.Keys | Sort-Object)
foreach ($cluster in $clusterNames) {
  [void]$sb.AppendLine("    ${cluster}:")
  [void]$sb.AppendLine("      children:")
  [void]$sb.AppendLine("        ${cluster}_masters:")
  [void]$sb.AppendLine("          hosts:")
  foreach ($m in $byCluster[$cluster].masters) {
    [void]$sb.AppendLine("            $($m.name):")
    [void]$sb.AppendLine("              ansible_host: $($m.ip)")
    [void]$sb.AppendLine("              node_role: master")
    [void]$sb.AppendLine("              cluster_name: $cluster")
  }
  [void]$sb.AppendLine("        ${cluster}_workers:")
  [void]$sb.AppendLine("          hosts:")
  foreach ($w in $byCluster[$cluster].workers) {
    [void]$sb.AppendLine("            $($w.name):")
    [void]$sb.AppendLine("              ansible_host: $($w.ip)")
    [void]$sb.AppendLine("              node_role: worker")
    [void]$sb.AppendLine("              cluster_name: $cluster")
  }
}

[void]$sb.AppendLine("    k8s_masters:")
[void]$sb.AppendLine("      children:")
foreach ($cluster in $clusterNames) {
  [void]$sb.AppendLine("        ${cluster}_masters:")
}
[void]$sb.AppendLine("    k8s_workers:")
[void]$sb.AppendLine("      children:")
foreach ($cluster in $clusterNames) {
  [void]$sb.AppendLine("        ${cluster}_workers:")
}
[void]$sb.AppendLine("    k8s_nodes:")
[void]$sb.AppendLine("      children:")
[void]$sb.AppendLine("        k8s_masters:")
[void]$sb.AppendLine("        k8s_workers:")

[IO.File]::WriteAllText($OutputPath, $sb.ToString())
Write-Host "Wrote Ansible inventory: $OutputPath"
