<#
  Discovers Hyper-V guest IPs for lab VMs and writes an Ansible inventory YAML.
#>
param(
  [Parameter(Mandatory = $true)]
  [string[]]$VmNames,

  [Parameter(Mandatory = $true)]
  [string]$OutputPath,

  [string]$SshUser = "ubuntu",
  [string]$SshPrivateKeyPath = "",
  [int]$WaitSeconds = 300,
  [int]$PollSeconds = 10
)

$ErrorActionPreference = "Stop"

function Get-GuestIpv4 {
  param([string]$Name)
  $adapter = Get-VMNetworkAdapter -VMName $Name -ErrorAction SilentlyContinue
  if (-not $adapter) { return $null }
  $ips = @($adapter.IPAddresses | Where-Object {
      $_ -match '^\d+\.\d+\.\d+\.\d+$' -and $_ -notlike '169.254.*'
    })
  if ($ips.Count -gt 0) { return $ips[0] }
  return $null
}

$deadline = (Get-Date).AddSeconds($WaitSeconds)
$resolved = @{}
# One soft reboot for guests still without an IP after this many seconds
# (stuck cloud-init / networking often recovers after Restart-VM).
$restartAfterSeconds = [Math]::Min(120, [Math]::Max(60, [int]($WaitSeconds / 3)))
$restarted = @{}

Write-Host "Waiting up to $WaitSeconds seconds for guest IPs..."
while ((Get-Date) -lt $deadline) {
  $pending = @()
  foreach ($name in $VmNames) {
    if ($resolved.ContainsKey($name)) { continue }
    $ip = Get-GuestIpv4 -Name $name
    if ($ip) {
      $resolved[$name] = $ip
      Write-Host "  $name -> $ip"
    } else {
      $pending += $name
    }
  }
  if ($pending.Count -eq 0) { break }

  $elapsed = $WaitSeconds - ($deadline - (Get-Date)).TotalSeconds
  if ($elapsed -ge $restartAfterSeconds) {
    foreach ($name in $pending) {
      if ($restarted.ContainsKey($name)) { continue }
      $vm = Get-VM -Name $name -ErrorAction SilentlyContinue
      if (-not $vm) { continue }
      Write-Host "  no IP yet for $name after ${restartAfterSeconds}s; restarting VM once..."
      try {
        Restart-VM -Name $name -Force -ErrorAction Stop
        $restarted[$name] = $true
      } catch {
        Write-Warning "  Restart-VM failed for ${name}: $_"
      }
    }
  }

  Write-Host ("  still waiting: " + ($pending -join ", "))
  Start-Sleep -Seconds $PollSeconds
}

$missing = @($VmNames | Where-Object { -not $resolved.ContainsKey($_) })
if ($missing.Count -gt 0) {
  throw "Timed out waiting for guest IPs: $($missing -join ', '). Ensure VMs are running and hv-kvp / guest services are available."
}

# Group by naming convention: <env>-<cluster>-<role>-<n>
$byCluster = @{}
foreach ($name in $VmNames) {
  $parts = $name -split "-"
  if ($parts.Count -lt 4) {
    throw "Unexpected VM name '$name' (expected <env>-<cluster>-<role>-<n>)"
  }
  $cluster = $parts[1]
  $role = $parts[2]
  if (-not $byCluster.ContainsKey($cluster)) {
    $byCluster[$cluster] = @{ masters = @(); workers = @() }
  }
  $entry = @{ name = $name; ip = $resolved[$name]; role = $role }
  if ($role -eq "master") {
    $byCluster[$cluster].masters += $entry
  } else {
    $byCluster[$cluster].workers += $entry
  }
}

$outDir = Split-Path -Parent $OutputPath
if (-not (Test-Path $outDir)) {
  New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$keyLine = if ($SshPrivateKeyPath) {
  "  ansible_ssh_private_key_file: $($SshPrivateKeyPath -replace '\\','/')"
} else {
  ""
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("---")
[void]$sb.AppendLine("# Generated by discover-inventory.ps1 - do not edit by hand.")
[void]$sb.AppendLine("all:")
[void]$sb.AppendLine("  vars:")
[void]$sb.AppendLine("    ansible_user: $SshUser")
[void]$sb.AppendLine("    ansible_python_interpreter: /usr/bin/python3")
if ($keyLine) { [void]$sb.AppendLine($keyLine) }
[void]$sb.AppendLine("  children:")

$clusterNames = @($byCluster.Keys | Sort-Object)
foreach ($cluster in $clusterNames) {
  [void]$sb.AppendLine("    ${cluster}:")
  [void]$sb.AppendLine("      children:")
  [void]$sb.AppendLine("        ${cluster}_masters:")
  [void]$sb.AppendLine("          hosts:")
  foreach ($m in $byCluster[$cluster].masters) {
    [void]$sb.AppendLine("            $($m.name):")
    [void]$sb.AppendLine("              ansible_host: $($m.ip)")
    [void]$sb.AppendLine("              node_role: master")
    [void]$sb.AppendLine("              cluster_name: $cluster")
  }
  [void]$sb.AppendLine("        ${cluster}_workers:")
  [void]$sb.AppendLine("          hosts:")
  foreach ($w in $byCluster[$cluster].workers) {
    [void]$sb.AppendLine("            $($w.name):")
    [void]$sb.AppendLine("              ansible_host: $($w.ip)")
    [void]$sb.AppendLine("              node_role: worker")
    [void]$sb.AppendLine("              cluster_name: $cluster")
  }
}

[void]$sb.AppendLine("    k8s_masters:")
[void]$sb.AppendLine("      children:")
foreach ($cluster in $clusterNames) {
  [void]$sb.AppendLine("        ${cluster}_masters:")
}
[void]$sb.AppendLine("    k8s_workers:")
[void]$sb.AppendLine("      children:")
foreach ($cluster in $clusterNames) {
  [void]$sb.AppendLine("        ${cluster}_workers:")
}
[void]$sb.AppendLine("    k8s_nodes:")
[void]$sb.AppendLine("      children:")
[void]$sb.AppendLine("        k8s_masters:")
[void]$sb.AppendLine("        k8s_workers:")

[IO.File]::WriteAllText($OutputPath, $sb.ToString())
Write-Host "Wrote Ansible inventory: $OutputPath"
