---
cluster_name: cluster2
cluster_group: cluster2
pod_network_cidr: "{{ lab_pod_cidrs[lab_env][cluster_name] }}"
service_cidr: "{{ lab_service_cidrs[lab_env][cluster_name] }}"
istio_cluster_name: cluster2
istio_network: "{{ lab_istio_networks[lab_env][cluster_name] }}"
kubeconfig_local_path: "{{ kubeconfig_dir }}/{{ lab_env }}-cluster2.conf"
