<#
.SYNOPSIS
  Generate ubuntu26.auto.pkrvars.hcl for this host (SSH key + local cloud VHDX paths).

.DESCRIPTION
  Packer requires ssh_private_key_path with no default. This script writes the
  gitignored auto vars file so deploy-lab / packer build work without hand-copying
  the .example file. Safe to re-run; overwrites machine-local paths each time.
#>
param(
  [string]$SshPrivateKeyPath = "$env:USERPROFILE\.ssh\id_ed25519",
  [string]$SshUsername = "ubuntu",
  [string]$SwitchName = "hyper-v-switch",
  [string]$OutputVhdxName = "ubuntu-26.04-server-cloudimg-amd64.vhdx"
)

$ErrorActionPreference = "Stop"

$packerDir = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$varsPath = Join-Path $packerDir "ubuntu26.auto.pkrvars.hcl"
$vhdxPath = Join-Path $packerDir "artifacts\$OutputVhdxName"

if (-not (Test-Path $SshPrivateKeyPath)) {
  throw "SSH private key not found: $SshPrivateKeyPath"
}

# Packer file:/// URLs need forward slashes and a drive letter (file:///D:/...).
$vhdxFull = [IO.Path]::GetFullPath($vhdxPath) -replace '\\', '/'
if ($vhdxFull -notmatch '^[A-Za-z]:/') {
  throw "Unexpected VHDX path (need a Windows drive letter): $vhdxFull"
}
$cloudImageUrl = "file:///$vhdxFull"
$keyPath = ([IO.Path]::GetFullPath($SshPrivateKeyPath) -replace '\\', '/')

$content = @"
# Auto-generated by scripts/write-packer-vars.ps1 - do not commit.
# Re-run that script (or deploy-lab.ps1) to refresh paths for this machine.

cloud_image_url       = "$cloudImageUrl"
cloud_image_checksum  = "none"
nocloud_iso_relpath   = "artifacts/nocloud-seed.iso"
ssh_private_key_path  = "$keyPath"
ssh_username          = "$SshUsername"

vm_name            = "ubuntu26-hyperv-packer"
switch_name        = "$SwitchName"
generation         = 2
cpus               = 2
memory             = 4096
disk_size_mb       = 40960
output_directory   = "output-ubuntu26-hyperv"
artifact_suffix    = ""
"@

Set-Content -Path $varsPath -Value $content -Encoding utf8
Write-Host "Wrote Packer vars: $varsPath" -ForegroundColor Green
Write-Host "  ssh_private_key_path = $keyPath"
Write-Host "  cloud_image_url      = $cloudImageUrl"
